apiVersion: v1
kind: Template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: brigadecore-brigade-worker
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: brigadecore/brigade-worker:v1.0.0
      from:
        kind: DockerImage
        name: brigadecore/brigade-worker:v1.0.0
      generation: null
      importPolicy: {}
      name: v1.0.0
      referencePolicy:
        type: Local
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: brigade-worker
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: brigade-worker
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: brigade-worker:latest
    postCommit: {}
    resources: {}
    source:
      dockerfile: |-
        FROM brigadecore/brigade-worker:v1.0.0
        RUN chgrp -R 0 /home/src && chmod -R g=u /home/src
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: brigadecore-brigade-worker:v1.0.0
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0